import type { MonthlyMissionDefinition } from "./monthlyMission.types";

/**
 * Full pool of possible monthly missions.
 * Each month picks 6 from this list using a deterministic seed.
 * Add new entries here to expand the pool — no other code changes needed.
 */
export const MISSION_POOL: MonthlyMissionDefinition[] = [
  // ── Combat ──────────────────────────────────────────────────
  {
    id: "combat_4",
    title: "4 sesiones de combate",
    description: "Completa 4 sesiones de combate este mes.",
    category: "Combate",
    metricId: "current_month_combat_sessions",
    targetValue: 4,
    rewardXp: 100,
    difficulty: "normal",
    weight: 3,
  },
  {
    id: "combat_6",
    title: "6 sesiones de combate",
    description: "Seis sesiones de combate en un mes. Constancia.",
    category: "Combate",
    metricId: "current_month_combat_sessions",
    targetValue: 6,
    rewardXp: 160,
    difficulty: "hard",
    weight: 2,
  },
  {
    id: "combat_2",
    title: "2 sesiones de combate",
    description: "Empieza el mes con combate.",
    category: "Combate",
    metricId: "current_month_combat_sessions",
    targetValue: 2,
    rewardXp: 60,
    difficulty: "easy",
    weight: 2,
  },
  // ── Strength ──────────────────────────────────────────────────
  {
    id: "strength_2",
    title: "2 sesiones de fuerza",
    description: "Registra 2 entrenos de fuerza este mes.",
    category: "Fuerza",
    metricId: "current_month_strength_sessions",
    targetValue: 2,
    rewardXp: 80,
    difficulty: "easy",
    weight: 3,
  },
  {
    id: "strength_4",
    title: "4 sesiones de fuerza",
    description: "Cuatro sesiones de pesas o fuerza.",
    category: "Fuerza",
    metricId: "current_month_strength_sessions",
    targetValue: 4,
    rewardXp: 130,
    difficulty: "normal",
    weight: 2,
  },
  // ── Endurance ─────────────────────────────────────────────────
  {
    id: "endurance_3",
    title: "3 sesiones de resistencia",
    description: "Carrera, natación, caminata o ruta.",
    category: "Resistencia",
    metricId: "current_month_endurance_sessions",
    targetValue: 3,
    rewardXp: 90,
    difficulty: "normal",
    weight: 3,
  },
  {
    id: "endurance_route",
    title: "Completa una ruta de 20 km",
    description: "Una sola ruta de al menos 20 km.",
    category: "Resistencia",
    metricId: "longest_route_km",
    targetValue: 20,
    rewardXp: 150,
    difficulty: "hard",
    weight: 1,
  },
  // ── Finance ───────────────────────────────────────────────────
  {
    id: "savings_300",
    title: "Ahorra 300 €",
    description: "Registra al menos 300 € de ahorro este mes.",
    category: "Finanzas",
    metricId: "current_month_savings_eur",
    targetValue: 300,
    rewardXp: 120,
    difficulty: "normal",
    weight: 2,
  },
  {
    id: "savings_500",
    title: "Ahorra 500 €",
    description: "Un mes con 500 € guardados.",
    category: "Finanzas",
    metricId: "current_month_savings_eur",
    targetValue: 500,
    rewardXp: 200,
    difficulty: "hard",
    weight: 1,
  },
  {
    id: "savings_100",
    title: "Ahorra 100 €",
    description: "El primer paso es siempre el más importante.",
    category: "Finanzas",
    metricId: "current_month_savings_eur",
    targetValue: 100,
    rewardXp: 60,
    difficulty: "easy",
    weight: 2,
  },
  // ── Constancy ─────────────────────────────────────────────────
  {
    id: "active_days_5",
    title: "5 días activos distintos",
    description: "Registra actividad en al menos 5 días del mes.",
    category: "Constancia",
    metricId: "current_month_active_days",
    targetValue: 5,
    rewardXp: 100,
    difficulty: "normal",
    weight: 3,
  },
  {
    id: "active_days_8",
    title: "8 días activos distintos",
    description: "Más de dos semanas con algún registro.",
    category: "Constancia",
    metricId: "current_month_active_days",
    targetValue: 8,
    rewardXp: 180,
    difficulty: "hard",
    weight: 2,
  },
  {
    id: "active_days_3",
    title: "3 días activos distintos",
    description: "Tres días con actividad. Empieza.",
    category: "Constancia",
    metricId: "current_month_active_days",
    targetValue: 3,
    rewardXp: 50,
    difficulty: "easy",
    weight: 2,
  },
  {
    id: "total_sessions_8",
    title: "8 sesiones en total",
    description: "Cualquier tipo de actividad, ocho veces.",
    category: "Constancia",
    metricId: "current_month_total_sessions",
    targetValue: 8,
    rewardXp: 140,
    difficulty: "normal",
    weight: 3,
  },
  {
    id: "total_sessions_12",
    title: "12 sesiones en total",
    description: "Tres sesiones por semana durante todo el mes.",
    category: "Constancia",
    metricId: "current_month_total_sessions",
    targetValue: 12,
    rewardXp: 220,
    difficulty: "hard",
    weight: 1,
  },
];
