import type {
  AchievementLevel,
  AchievementRarity,
  AchievementSeries,
  RewardType,
} from "./achievement.types";

function level(
  levelNumber: number,
  label: string,
  threshold: number,
  xpReward: number,
  rarity: AchievementRarity,
  rewardType: RewardType = levelNumber >= 4 ? "trophy" : levelNumber >= 3 ? "badge" : "star"
): AchievementLevel {
  return {
    level: levelNumber,
    label,
    threshold,
    xpReward,
    rarity,
    rewardType,
    description: `${label}: alcanza ${threshold}.`,
  };
}

function countLevels(values: number[]): AchievementLevel[] {
  return values.map((threshold, index) =>
    level(
      index + 1,
      index === values.length - 1 ? "Trofeo" : `Nivel ${index + 1}`,
      threshold,
      [25, 75, 175, 400][index] ?? 100,
      (["common", "rare", "epic", "legendary"] as AchievementRarity[])[index] ?? "common"
    )
  );
}

function series(input: Omit<AchievementSeries, "origin" | "status" | "isHidden" | "requiresMutualApproval">): AchievementSeries {
  return {
    origin: "system",
    status: "active",
    isHidden: false,
    requiresMutualApproval: false,
    ...input,
  };
}

export const ACHIEVEMENT_SERIES_CATALOG: AchievementSeries[] = [
  series({
    id: "cuerpo_a_cuerpo",
    name: "Cuerpo a cuerpo",
    description: "Acumula sesiones de combate.",
    category: "combat",
    icon: "🥊",
    rarity: "common",
    dependsOnMetric: "combat_sessions_total",
    relatedTemplateId: "combat_session",
    levels: countLevels([1, 5, 20, 50]),
  }),
  series({
    id: "a_cielo_abierto",
    name: "A cielo abierto",
    description: "Entrena fuera de casa o del gimnasio.",
    category: "combat",
    icon: "🌤️",
    rarity: "rare",
    dependsOnMetric: "outdoor_sessions_total",
    relatedTemplateId: "combat_session",
    levels: countLevels([1, 5, 20, 50]),
  }),
  series({
    id: "horno",
    name: "Horno",
    description: "Registra sesiones con calor extremo.",
    category: "conditions",
    icon: "🔥",
    rarity: "epic",
    dependsOnMetric: "extreme_heat_sessions_total",
    relatedTemplateId: "combat_session",
    levels: countLevels([1, 3, 10, 25]),
  }),
  series({
    id: "sesion_intensa",
    name: "Sesion intensa",
    description: "Completa sesiones de intensidad alta.",
    category: "combat",
    icon: "⚡",
    rarity: "rare",
    dependsOnMetric: "intense_sessions_total",
    relatedTemplateId: "combat_session",
    levels: countLevels([1, 5, 20, 50]),
  }),
  series({
    id: "forjador_de_hierro",
    name: "Forjador de hierro",
    description: "Constancia en entrenamientos de fuerza.",
    category: "strength",
    icon: "🏋️",
    rarity: "common",
    dependsOnMetric: "strength_sessions_total",
    relatedTemplateId: "strength_session",
    levels: countLevels([1, 10, 30, 100]),
  }),
  series({
    id: "press_banca",
    name: "Press banca",
    description: "Sube tu marca maxima de press banca.",
    category: "strength",
    icon: "🏋️",
    rarity: "rare",
    dependsOnMetric: "bench_press_max_kg",
    relatedTemplateId: "strength_session",
    levels: [
      level(1, "Bronce", 80, 50, "common"),
      level(2, "Plata", 100, 125, "rare"),
      level(3, "Oro", 120, 250, "epic", "badge"),
      level(4, "Legendario", 140, 500, "legendary", "trophy"),
    ],
  }),
  series({
    id: "peso_muerto",
    name: "Peso muerto",
    description: "Sube tu marca maxima de peso muerto.",
    category: "strength",
    icon: "💪",
    rarity: "rare",
    dependsOnMetric: "deadlift_max_kg",
    relatedTemplateId: "strength_session",
    levels: [
      level(1, "Bronce", 120, 50, "common"),
      level(2, "Plata", 160, 125, "rare"),
      level(3, "Oro", 200, 250, "epic", "badge"),
      level(4, "Legendario", 240, 500, "legendary", "trophy"),
    ],
  }),
  series({
    id: "sentadilla",
    name: "Sentadilla",
    description: "Sube tu marca maxima de sentadilla.",
    category: "strength",
    icon: "🦵",
    rarity: "rare",
    dependsOnMetric: "squat_max_kg",
    relatedTemplateId: "strength_session",
    levels: [
      level(1, "Bronce", 100, 50, "common"),
      level(2, "Plata", 140, 125, "rare"),
      level(3, "Oro", 180, 250, "epic", "badge"),
      level(4, "Legendario", 220, 500, "legendary", "trophy"),
    ],
  }),
  series({
    id: "poseidon",
    name: "Poseidon",
    description: "Acumula sesiones de natacion.",
    category: "endurance",
    icon: "🏊",
    rarity: "common",
    dependsOnMetric: "swimming_sessions_total",
    relatedTemplateId: "swimming_session",
    levels: countLevels([1, 5, 20, 50]),
  }),
  series({
    id: "ruta_larga",
    name: "Ruta larga",
    description: "Completa rutas cada vez mas largas.",
    category: "endurance",
    icon: "🗺️",
    rarity: "rare",
    dependsOnMetric: "longest_route_km",
    relatedTemplateId: "route_session",
    levels: [
      level(1, "20 km", 20, 50, "common"),
      level(2, "40 km", 40, 125, "rare"),
      level(3, "60 km", 60, 250, "epic", "badge"),
      level(4, "100 km", 100, 500, "legendary", "trophy"),
    ],
  }),
  series({
    id: "caminador",
    name: "Caminador",
    description: "Suma caminatas registradas.",
    category: "endurance",
    icon: "🚶",
    rarity: "common",
    dependsOnMetric: "walking_sessions_total",
    relatedTemplateId: "walking_session",
    levels: countLevels([1, 10, 30, 100]),
  }),
  series({
    id: "corredor",
    name: "Corredor",
    description: "Suma carreras registradas.",
    category: "endurance",
    icon: "🏃",
    rarity: "common",
    dependsOnMetric: "running_sessions_total",
    relatedTemplateId: "running_session",
    levels: countLevels([1, 10, 30, 100]),
  }),
  series({
    id: "madrugador",
    name: "Madrugador",
    description: "Registra sesiones por la manana.",
    category: "conditions",
    icon: "🌅",
    rarity: "common",
    dependsOnMetric: "morning_sessions_total",
    relatedTemplateId: "running_session",
    levels: countLevels([1, 5, 20, 50]),
  }),
  series({
    id: "nocturno",
    name: "Nocturno",
    description: "Registra sesiones de noche.",
    category: "conditions",
    icon: "🌙",
    rarity: "common",
    dependsOnMetric: "night_sessions_total",
    relatedTemplateId: "running_session",
    levels: countLevels([1, 5, 20, 50]),
  }),
  series({
    id: "bajo_la_lluvia",
    name: "Bajo la lluvia",
    description: "Entrena con lluvia.",
    category: "conditions",
    icon: "🌧️",
    rarity: "rare",
    dependsOnMetric: "rain_sessions_total",
    relatedTemplateId: "running_session",
    levels: countLevels([1, 5, 20, 50]),
  }),
  series({
    id: "caja_fuerte",
    name: "Caja fuerte",
    description: "Ahorro acumulado del mes actual.",
    category: "finance",
    icon: "🔒",
    rarity: "rare",
    dependsOnMetric: "current_month_savings_eur",
    relatedTemplateId: "finance_saving",
    levels: [
      level(1, "100 EUR", 100, 40, "common"),
      level(2, "300 EUR", 300, 100, "rare"),
      level(3, "500 EUR", 500, 200, "epic", "badge"),
      level(4, "1000 EUR", 1000, 450, "legendary", "trophy"),
    ],
  }),
  series({
    id: "primer_ahorro",
    name: "Primer ahorro",
    description: "Constancia registrando ahorros.",
    category: "finance",
    icon: "💰",
    rarity: "common",
    dependsOnMetric: "saving_events_total",
    relatedTemplateId: "finance_saving",
    levels: countLevels([1, 5, 20, 50]),
  }),
  series({
    id: "victoria",
    name: "Victoria",
    description: "Completa retos.",
    category: "challenges",
    icon: "🏆",
    rarity: "common",
    dependsOnMetric: "completed_challenges_total",
    relatedTemplateId: "challenge_result",
    levels: countLevels([1, 5, 20, 50]),
  }),
  series({
    id: "duelista",
    name: "Duelista",
    description: "Gana duelos contra Rival.",
    category: "challenges",
    icon: "⚔️",
    rarity: "rare",
    dependsOnMetric: "duel_wins_total",
    relatedTemplateId: "challenge_result",
    levels: countLevels([1, 5, 20, 50]),
  }),
  series({
    id: "primer_paso",
    name: "Primer paso",
    description: "La primera sesion registrada.",
    category: "constancy",
    icon: "👣",
    rarity: "common",
    dependsOnMetric: "all_sessions_total",
    relatedTemplateId: "manual_action",
    levels: [level(1, "Primer paso", 1, 25, "common")],
  }),
  series({
    id: "semana_activa",
    name: "Semana activa",
    description: "Sesiones registradas durante la semana actual.",
    category: "constancy",
    icon: "📅",
    rarity: "rare",
    dependsOnMetric: "current_week_sessions_total",
    relatedTemplateId: "running_session",
    levels: [
      level(1, "3 sesiones", 3, 40, "common"),
      level(2, "5 sesiones", 5, 100, "rare"),
      level(3, "7 sesiones", 7, 200, "epic", "badge"),
    ],
  }),
  series({
    id: "disciplina",
    name: "Disciplina",
    description: "Dias activos distintos acumulados.",
    category: "constancy",
    icon: "✅",
    rarity: "epic",
    dependsOnMetric: "distinct_active_days_total",
    relatedTemplateId: "manual_action",
    levels: [
      level(1, "7 dias", 7, 50, "common"),
      level(2, "30 dias", 30, 150, "rare"),
      level(3, "100 dias", 100, 400, "epic", "badge"),
      level(4, "365 dias", 365, 1200, "legendary", "trophy"),
    ],
  }),
];

export const ACHIEVEMENT_SERIES_BY_ID = Object.fromEntries(
  ACHIEVEMENT_SERIES_CATALOG.map((seriesItem) => [seriesItem.id, seriesItem])
) as Record<string, AchievementSeries>;
